# Generated by Django 3.0.3 on 2020-09-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='link',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
