# Generated by Django 3.0.3 on 2020-09-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200916_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('name_1', models.TextField(blank=True, null=True)),
                ('number_1', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('name_2', models.TextField(blank=True, null=True)),
                ('number_2', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('name_3', models.TextField(blank=True, null=True)),
                ('number_3', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
            ],
        ),
    ]
