# Generated by Django 3.0.3 on 2020-09-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200916_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='amazon'),
        ),
    ]
