# Generated by Django 3.0.3 on 2020-09-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_amazon_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='slider')),
                ('link', models.CharField(blank=True, max_length=64, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
