# Generated by Django 3.0.3 on 2020-09-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
